### PR TITLE
Update dependencies for security

### PR DESCRIPTION
**Pull request by robinske**
Updating dependencies per warnings https://github.com/twilio/authy-ruby/network/alerts

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by robinske** [comment]
Travis throwing error
```
You must use Bundler 2 or greater with this lockfile.
```

Looks like we'll have to do some configuration around the bundler version, easiest thing would be to drop support for Ruby 2.2 - is that a reasonable option @senekis ? 

https://docs.travis-ci.com/user/languages/ruby/

**Comment by philnash** [comment]
Ruby 2.3 is EOL, so 2.2 definitely shouldn't require our attention.

**Comment by robinske** [comment]
Ah good catch @philnash, updated!

**Comment by philnash** [comment]
I don't think we need this any more after merging #65.

**Pull request closed without merging**
